on:
  push:
    tags:
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate Release Notes
      id: generate_release_notes
      run: |
        echo "## Changelog" > ../release_notes.md
        git log --pretty=format:"* %s (%h)" $(git describe --tags --abbrev=0 @^)..@ >> ../release_notes.md
        echo "release_notes=${PWD}/../release_notes.md" >> "$GITHUB_OUTPUT"

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends autoconf automake libtool gettext
        sudo apt install -y --no-install-recommends intltool libglib2.0-dev

    - name: Make tarball
      id: tarball
      run: |
        SRC="$PWD"
        VER="${{ github.ref }}"
        VER="$(printf '%s\n' "${VER##*/}")"
        DST="$SRC-$VER"
        cd ..
        cp -a "$SRC" "$DST"
        cd "$DST"
        rm -rf .git*
        autoreconf -i
        cd ..
        tar -cf "$DST".tar "$DST"
        xz -9 "$DST".tar
        echo "tarball_xz=${DST}.tar.xz" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body_path: ${{ steps.generate_release_notes.outputs.release_notes }}
        files: |
          ${{ steps.tarball.outputs.tarball_xz }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
